# Create with NumPy the following 2D array

| 1 	| 1 	| 1 	| 1 	| 1 	|
|---	|---	|---	|---	|---	|
| 1 	| 0 	| 0 	| 0 	| 1 	|
| 1 	| 0 	| 9 	| 0 	| 1 	|
| 1 	| 0 	| 0 	| 0 	| 0 	|
| 1 	| 1 	| 1 	| 1 	| 1 	|

In [14]:
import numpy as np
output = np.ones((5,5), dtype='int32')


z = np.zeros((3,3))
z[1,1] = 9

output[1:-1, 1: -1] = z
print(output)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


### Find the following cells using the methods we have learned so far:

| 1 	| 2 	| 3 	| 4 	| 5 	|
|---	|---	|---	|---	|---	|
| 6 	| 7 	| 8 	| 9 	| 10 	|
| 11 	| 12 	| 13 	| 14 	| 15 	|
| 16 	| 17 	| 18 	| 19 	| 20 	|
| 21 	| 22 	| 23 	| 24 	| 25 	|
| 26 	| 27 	| 28 	| 29 	| 30 	|

In [31]:
a = np.array([[1,2,3,4,5], [6,7,8,9,10],[11,12,13,14,15], [16,17,18,19,20], [21,22,23,24,25],[26,27,28,29,30]])

print(a[2:4, 0:2])
print(a[[0,1,2,3],[1,2,3,4]])

[[11 12]
 [16 17]]
[ 2  8 14 20]
