# Load in Numpy (remember to pip install numpy first)

In [13]:
import numpy as np

# creating arrays

In [3]:
a =  np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
b = np.array([[1,2,3], [4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


### Dimention, Shape, Type, Size

In [5]:
a.ndim

1

In [9]:
a.shape

(3,)

In [10]:
a.dtype

dtype('int64')

In [15]:
a.size

3

### Array Operations - get all row / columm

In [52]:
c = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14],[15,16,17,18,19,20,21]])
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]]


In [54]:
# get a specific row
c[1, :]

array([ 8,  9, 10, 11, 12, 13, 14])

In [55]:
# get a specific row
c[:, 2]

array([ 3, 10, 17])

In [57]:
# getting a little more fancy []startindex:endindex:stepsize]
c[0,1:6:2]

array([2, 4, 6])

### Create default arrays, zeros, ones

In [58]:
np.zeros((2, 3, 3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [59]:
# All 1s matrix & int32
np.ones((2,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [60]:
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [61]:
# Replace element in array
c[0:-1,1:-1]

array([[ 2,  3,  4,  5,  6],
       [ 9, 10, 11, 12, 13]])

### Mathematics

In [67]:
a = np.array([1,2,3,4])

In [68]:
a + 2

array([3, 4, 5, 6])

In [69]:
a - 2

array([-1,  0,  1,  2])

In [70]:
a * 2

array([2, 4, 6, 8])

In [71]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [73]:
b = np.array([1,0,1,0])

In [75]:
a + b

array([2, 2, 4, 4])

In [77]:
a ** 2

array([ 1,  4,  9, 16])